name: Tests and build

on: 
  push:
    branches:    
      - main  
    paths:
      - 'aws-rds/backend/**'
      - 'aws-rds/frontend/**'
  pull_request:
    paths:
      - 'aws-rds/backend/**'
      - 'aws-rds/frontend/**'

jobs:
  build:
    if: github.event_name == 'pull_request'
    uses: DVES-Consult/github-reusable/.github/workflows/build-and-push-docker-image.yml@main
    secrets: inherit
  
  merge:
    if: github.event_name == 'push'
    uses: DVES-Consult/github-reusable/.github/workflows/merge-main.yml@main
    secrets: inherit

